### ISSUE TITLE
Contribute back to lottie-react-native?

### ISSUE THREAD

**Issue by gpeal** [bamlab/easy-lottie-react-native#1]
Are you interested in upstreaming some of the work you've done to the main library? I've been mainly focusing on Android so I'd gladly accept the help :)

**Comment by gpeal** [comment]
@Minishlink

**Comment by Minishlink** [comment]
Sure @gpeal, I'll see what I can do. :)

**Comment by Minishlink** [comment]
I'm archiving this repo since the improvements of this library were upstreamed. Thanks @gpeal!
